[package]
name = "week2"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
openssl = "0.10.43"
des = "0.8.1"
generic-array = "0.14.6"